export const loginUri = 'auth/login'
export const getReferenceUri = 'auth'
export const emailCheckUri = 'auth/email'
export const passwordCheckUri = 'auth/confirm'
export const passwordSaveUri = 'register/savepswd'
